services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=storage_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GOOGLE_BUCKET_NAME=your-google-bucket-name
      - GOOGLE_CLIENT_CALLBACK_URL=http://localhost:3000/auth/google/callback
    depends_on:
      - database
      - redis

  database:
    image: postgres:16.3
    container_name: storage_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storage_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:
